#!/bin/bash

# This file will clean up auxiliary files generated by pdflatex.
# I got the idea from Manuel Kuehner <https://bedienhaptik.de/latex-template/>
# who added a .bat file to the latex template he has published on his site.
# I have tested it on my machine which runs elementary 5.1.3

# Run this command first to grant permission
# chmod +x cleanup.sh

find . -type f -name '*.aux' -exec rm {} +
find . -type f -name '*.out' -exec rm {} +
find . -type f -name '*.idx' -exec rm {} +
find . -type f -name '*.ilg' -exec rm {} +
find . -type f -name '*.ind' -exec rm {} +
find . -type f -name '*.log' -exec rm {} +
find . -type f -name '*.lot' -exec rm {} +
find . -type f -name '*.lof' -exec rm {} +
find . -type f -name '*.maf' -exec rm {} +
find . -type f -name '*.mtc' -exec rm {} +
find . -type f -name '*.mtc0' -exec rm {} +
find . -type f -name '*.xml' -exec rm {} +
find . -type f -name '*.toc' -exec rm {} +
find . -type f -name '*.ent' -exec rm {} +


echo "Done cleaning up the working directory."
